"""add ecological columns to lakes

Revision ID: 0b51613d63d8
Revises: 9615b1b5686d
Create Date: 2026-01-02 21:59:34.450260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b51613d63d8'
down_revision: Union[str, Sequence[str], None] = '9615b1b5686d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lakes', sa.Column('Z', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('H', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('G', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('A', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('D', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('W', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('T', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('Tw', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('pH', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('O', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('I', sa.String(), nullable=True))
    op.add_column('lakes', sa.Column('M', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('Thw', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('Ka', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('SAR', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('IIWP_Dc', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('Tr', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('Fl', sa.Integer(), nullable=True))
    op.add_column('lakes', sa.Column('Fa', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lakes', 'Fa')
    op.drop_column('lakes', 'Fl')
    op.drop_column('lakes', 'Tr')
    op.drop_column('lakes', 'IIWP_Dc')
    op.drop_column('lakes', 'SAR')
    op.drop_column('lakes', 'Ka')
    op.drop_column('lakes', 'Thw')
    op.drop_column('lakes', 'M')
    op.drop_column('lakes', 'I')
    op.drop_column('lakes', 'O')
    op.drop_column('lakes', 'pH')
    op.drop_column('lakes', 'Tw')
    op.drop_column('lakes', 'T')
    op.drop_column('lakes', 'W')
    op.drop_column('lakes', 'D')
    op.drop_column('lakes', 'A')
    op.drop_column('lakes', 'G')
    op.drop_column('lakes', 'H')
    op.drop_column('lakes', 'Z')
    # ### end Alembic commands ###
