"""create coordinates table

Revision ID: 7f8fd55ec58e
Revises: ab463c56ebd1
Create Date: 2026-01-30 11:50:11.604554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8fd55ec58e'
down_revision: Union[str, Sequence[str], None] = 'ab463c56ebd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_object_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['water_object_id'], ['water_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordinates_id'), 'coordinates', ['id'], unique=False)
    op.drop_index(op.f('ix_lakes_id'), table_name='water_objects')
    op.create_index(op.f('ix_water_objects_id'), 'water_objects', ['id'], unique=False)
    op.alter_column('water_quality', 'water_object_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_water_quality_id'), 'water_quality', ['id'], unique=False)
    op.drop_constraint(op.f('water_quality_water_object_id_fkey'), 'water_quality', type_='foreignkey')
    op.create_foreign_key(None, 'water_quality', 'water_objects', ['water_object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'water_quality', type_='foreignkey')
    op.create_foreign_key(op.f('water_quality_water_object_id_fkey'), 'water_quality', 'water_objects', ['water_object_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_water_quality_id'), table_name='water_quality')
    op.alter_column('water_quality', 'water_object_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_water_objects_id'), table_name='water_objects')
    op.create_index(op.f('ix_lakes_id'), 'water_objects', ['id'], unique=False)
    op.drop_index(op.f('ix_coordinates_id'), table_name='coordinates')
    op.drop_table('coordinates')
    # ### end Alembic commands ###
